image: docker
services:
   - docker:dind

stages:
   - build

build:
   stage: build
   script:
      - docker build -t alexgoris/maker-dash:latest .
      - docker login -u $REG_UN -p $REG_PW
      - docker push alexgoris/maker-dash
