version: '2'

services:  
  ci-build:
    image: images4build/dotnetbuilder
    container_name: build
    volumes:
      - .:/src
    working_dir: /src/
    command: /bin/bash -c "dotnet restore && dotnet publish -c Release -o ./build"